name: Clayagogo
favicon: null
layout_spectrum: 0.94838
typography_spectrum: 0.16851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#f882bf'
    - '#323232'
    - '#6a6a6a'
  brandStrength: 0.3788780211471021
  lightness: 0.3782558592502028
  saturation: 0.8701191139407456
  rhythmicContrast: 0.7568297344259918
purpose: []
